TST: Move assert call into eq_repr
Otherwise pytest can't do its assertion introspection.

This gets us something like

    >       assert repr(a) == repr(b)
    E       assert "'\\x1b[32mfo...(B\\x1b[m\\n'" == "'\\x1b[32mfoo...(B\\x1b[m\\n'"
    E         - '\x1b[32mfoo\x1b(B\x1b[m\n'
    E         + '\x1b[32mfooA\x1b(B\x1b[m\n'
    E         ?             +

instead of

    >       assert eq_repr(out.stdout, expected)
    E       AssertionError: assert False
    E        +  where False = eq_repr('\x1b[32mfoo\x1b(B\x1b[m\n', '\x1b[32mfooA\x1b(B\x1b[m\n')
    E        +    where '\x1b[32mfoo\x1b(B\x1b[m\n' = <pyout.tests.test_tabular.Tabular object at 0x7fee10330f60>.stdout