BF: Convert to string representation before formatting
Prevent a python3-dependent error when a list is passed as a value.

    py2> "{:5}".format([0, 1])
    '[0, 1]'

    py3> "{:5}".format([0, 1])
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unsupported format string passed to list.__format__